env:
  browser: true
  node: true
  jest: true
  es6: true
extends: 'eslint:recommended'
rules:
  curly:
    - error
    - all
  eqeqeq:
    - error
    - smart
  indent:
    - error
    - 2
    - { SwitchCase: 1 }
  object-curly-spacing:
    - error
    - always
  linebreak-style:
    - error
    - unix
  space-infix-ops:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-trailing-spaces:
    - error
    - { skipBlankLines: false }
