---
resources:
  - name: fauna-js-repository
    type: git
    icon: github
    source:
      uri: https://github.com/fauna/faunadb-js
      branch: oss-485-automate-js-driver-release-in-concourse-ci

  - name: fauna-js-repository-docs
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/faunadb-js.git
      branch: gh-pages-test
      private_key: ((fauna/repo.key))

  - name: nodejs-image
    type: registry-image
    source:
      repository: node
      tag: 15.14.0-alpine3.10

  - name: git-image
      type: registry-image
      source:
        repository: alpine/git
        tag: v2.30.2

  - name: dind-image
    type: registry-image
    source:
      repository: karlkfi/concourse-dcind

jobs:
  - name: integration
    public: false
    plan:
      - get: fauna-js-repository
      - get: dind-image
      - task: integration-tests
        image: dind-image
        privileged: true
        config:
          platform: linux
          inputs:
            - name: fauna-js-repository
          run:
            path: entrypoint.sh
            args:
              - bash
              - -ceux
              - |
                pwd
                ls -la ./fauna-js-repository
                # start containers
                docker-compose -f fauna-js-repository/concourse/integration.yml run -e FAUNA_ROOT_KEY=((fauna.secret)) -e FAUNA_DOMAIN=((fauna.domain)) -e FAUNA_SCHEME=((fauna.scheme)) -e FAUNA_PORT=((fauna.port)) -e AUTH_0_URI=((fauna/auth0.uri)) -e AUTH_0_CLIENT_ID=((fauna/auth0/client.id)) -e AUTH_0_CLIENT_SECRET=((fauna/auth0/client.secret)) tests
                # stop and remove containers
                docker-compose -f fauna-js-repository/concourse/integration.yml down
                # remove volumes
                docker volume rm $(docker volume ls -q)
  - name: publish
    public: false
    plan:
      - get: nodejs-image
      - get: fauna-js-repository
        passed: [integration]
        trigger: true
      - task: browserify-and-npm-publish
        image: nodejs-image
        privileged: true
        config:
          platform: linux
          inputs:
            - name: fauna-js-repository
          run:
            path: ./fauna-js-repository/concourse/publish.sh
  - name: publish-docs
    public: false
    plan:
      - get: nodejs-image
      - get: fauna-js-repository
      - get: fauna-js-repository-docs
        passed: [publish]
        trigger: true
      - task: generate-docs
        image: nodejs-image
        privileged: true
        config:
          platform: linux
          inputs:
            - name: fauna-js-repository
          outputs:
            - name: doc
            - name: docs_version
          run:
            path: ./fauna-js-repository/concourse/generate_docs.sh
      - task: publish-docs-to-git-repo
        image: git-image
        privileged: true
        config:
          platform: linux
          inputs:
            - name: doc
            - name: docs_version
            - name: fauna-js-repository
            - name: fauna-js-repository-docs
          outputs:
            - name: fauna-js-repository-updated-docs
          run:
            path: ./fauna-js-repository/concourse/publish_docs.sh
      - put: fauna-js-repository-docs
        params:
          repository: fauna-js-repository-updated-docs
