version: "3.3"

services:
  tests:
    environment:
      - FAUNA_ROOT_KEY
      - FAUNA_DOMAIN
      - FAUNA_SCHEME
      - FAUNA_PORT
      - AUTH_0_URI
      - AUTH_0_CLIENT_ID
      - AUTH_0_CLIENT_SECRET
    container_name: mytests
    depends_on:
      - faunadb
    volumes:
      - "../../:/tmp/app"
    working_dir: "/tmp/app"
    command: [sh, -c, "npm install && npm run build:package && npm test"]
