---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: karlkfi/concourse-dcind

params:
  FAUNA_ROOT_KEY:
  FAUNA_DOMAIN:
  FAUNA_SCHEME:
  FAUNA_PORT:
  AUTH_0_URI:
  AUTH_0_CLIENT_ID:
  AUTH_0_CLIENT_SECRET:
  FAUNA_REPO_PASSWORD:

inputs:
  - name: fauna-js-repository

run:
  path: entrypoint.sh
  args:
    - bash
    - -ceu
    - |
      docker login -u _json_key -p "$FAUNA_REPO_PASSWORD" https://gcr.io > /dev/null 2>&1
      # start containers
      docker-compose -f fauna-js-repository/concourse/tasks/integration.yml run test-10
      docker-compose -f fauna-js-repository/concourse/tasks/integration.yml run test-12
      docker-compose -f fauna-js-repository/concourse/tasks/integration.yml run test-14
      docker-compose -f fauna-js-repository/concourse/tasks/integration.yml run test-16
      # stop and remove containers
      docker-compose -f fauna-js-repository/concourse/tasks/integration.yml down
      # remove volumes
      docker volume rm $(docker volume ls -q)
